---
keys:
  - &host_gladius age13hry6wpjk5zvzwn7jy9mmcv2tjy5axk2ur8ky6c9n4kvj8tc4s8suqfvy3
  - &host_milton age1p5najec7uuhad6446xv0jasv89mam4aer9ansrmt7c5u5ymahvvqvv2qac
  - &user_bjw-s age1uk0y2ahfavgsgqvrtg5a22w5gytpdmjuatxtcw6kntmxhlcgreesuwzw5s

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_bjw-s
          - *host_gladius
          - *host_milton
