---
keys:
  - &host_gladius age1yf9ntkq86gy9u0qmffsklh2eurym5j00qswn0t2gfwrh9dj6s5ssgkyenf
  - &host_milton age16ppzg3tt5s0n9unwnqgqnu6clkj6wtfe4dsq63f7vccyamg6wg6qgfxu80
  - &user_bjw-s age1uk0y2ahfavgsgqvrtg5a22w5gytpdmjuatxtcw6kntmxhlcgreesuwzw5s

creation_rules:
  - path_regex: .*\.sops\.ya?ml$
    key_groups:
      - age:
          - *user_bjw-s
          - *host_gladius
          - *host_milton
