---
version: "3"

includes:
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops
  nix:
    taskfile: ".taskfiles/nix"
    dir: "{{.ROOT_DIR}}"

tasks:
  default:
    silent: true
    cmds:
      - task -l
