# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.

{ pkgs }:

let
  vscode-utils = pkgs.vscode-utils;
in
{

  "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
    name = "python";
    publisher = "ms-python";
    version = "2023.22.1";
    sha256 = "1cg41vli6g330fjpjyxf65ipzh1xjx3s4pdcqzkzqgl57y505ndy";
  };

  "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-pylance";
    publisher = "ms-python";
    version = "2023.12.1";
    sha256 = "03fr9zanhdsf3wirv65vb41swvdnxxaz8lviyjdbmzcw9yihf8dv";
  };

  "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "prettier-vscode";
    publisher = "esbenp";
    version = "10.1.0";
    sha256 = "01s0vi2h917mqfpdrhqhp2ijwkibw95yk2js0l587wvajbbry2s9";
  };

  "ms-azuretools"."vscode-docker" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-docker";
    publisher = "ms-azuretools";
    version = "1.28.0";
    sha256 = "0nmc3pdgxpmr6k2ksdczkv9bbwszncfczik0xjympqnd2k0ra9h0";
  };

  "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gitlens";
    publisher = "eamodio";
    version = "14.6.1";
    sha256 = "0nc6xv9rwfw92fnl089cvlrn3cqw21jkns8shkj1d0h1qiq4rh5q";
  };

  "ms-vscode-remote"."remote-containers" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-containers";
    publisher = "ms-vscode-remote";
    version = "0.327.0";
    sha256 = "0asswm55bx5gpz08cgpmgfvnb0494irj0gsvzx5nwknqfzpj07lz";
  };

  "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-ssh";
    publisher = "ms-vscode-remote";
    version = "0.107.1";
    sha256 = "1q9xp8id9afhjx67zc7a61zb572f296apvdz305xd5v4brqd9xrf";
  };

  "redhat"."vscode-yaml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-yaml";
    publisher = "redhat";
    version = "1.14.0";
    sha256 = "0pww9qndd2vsizsibjsvscz9fbfx8srrj67x4vhmwr581q674944";
  };

  "github"."copilot" = vscode-utils.extensionFromVscodeMarketplace {
    name = "copilot";
    publisher = "github";
    version = "1.143.0";
    sha256 = "08rna6k82hcbpdaglfl47kix54i5b6a4vs5wa64gkr55896vh74i";
  };

  "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
    name = "go";
    publisher = "golang";
    version = "0.40.0";
    sha256 = "1k2zv49pam436cgvb970dc9n4xpdkd07lp8jllrsx5vnx7m2ml52";
  };

  "gruntfuggly"."todo-tree" = vscode-utils.extensionFromVscodeMarketplace {
    name = "todo-tree";
    publisher = "gruntfuggly";
    version = "0.0.226";
    sha256 = "0yrc9qbdk7zznd823bqs1g6n2i5xrda0f9a7349kknj9wp1mqgqn";
  };

  "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-kubernetes-tools";
    publisher = "ms-kubernetes-tools";
    version = "1.3.15";
    sha256 = "1x6npc90p6b1wx5sd1hd0x0djahmffr6lw9cxh2zg10rbpq48w8i";
  };

  "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform";
    publisher = "hashicorp";
    version = "2.29.1";
    sha256 = "sha256-0XC0j0DQbRnu5k8HBgJSoYb7noj2jxFtgPvGazx0uyI=";
  };

  "ionutvmi"."path-autocomplete" = vscode-utils.extensionFromVscodeMarketplace {
    name = "path-autocomplete";
    publisher = "ionutvmi";
    version = "1.25.0";
    sha256 = "0jjqh3p456p1aafw1gl6xgxw4cqqzs3hssr74mdsmh77bjizcgcb";
  };

  "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "even-better-toml";
    publisher = "tamasfe";
    version = "0.19.2";
    sha256 = "0q9z98i446cc8bw1h1mvrddn3dnpnm2gwmzwv2s3fxdni2ggma14";
  };

  "redhat"."ansible" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ansible";
    publisher = "redhat";
    version = "2.9.118";
    sha256 = "0yndj2r0w2zxc5firxgfrykkc5ajy9gsmrfmkz80kfhwk33n9y1p";
  };

  "fnando"."linter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "linter";
    publisher = "fnando";
    version = "0.0.19";
    sha256 = "13bllbxd7sy4qlclh37qvvnjp1v13al11nskcf2a8pmnmj455v4g";
  };

  "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc";
    publisher = "catppuccin";
    version = "3.8.2";
    sha256 = "034rwrd56xcgnzfqvpbdhhhil7ihxdqqhfh2wikk6c1xvw52wiwl";
  };

  "mrmlnc"."vscode-json5" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-json5";
    publisher = "mrmlnc";
    version = "1.0.0";
    sha256 = "0bghvq89pp5s4liw11py8afyrlg4b02npv9ypnrnl0d2w99ab6aw";
  };

  "catppuccin"."catppuccin-vsc-icons" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc-icons";
    publisher = "catppuccin";
    version = "0.30.0";
    sha256 = "035rl1kx565h9s0xlh20pr6p26g9g9zy2l4zag0bn653lbm51jhg";
  };

  "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
    name = "nix-ide";
    publisher = "jnoortheen";
    version = "0.2.2";
    sha256 = "1264027sjh9a112si0y0p3pk3y36shj5b4qkpsj207z7lbxqq0wg";
  };

  "luisfontes19"."vscode-swissknife" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-swissknife";
    publisher = "luisfontes19";
    version = "1.8.1";
    sha256 = "1rpk8zayzkn2kg4jjdd2fy6xl50kib71dqg73v46326cr4dwxa7c";
  };

  "signageos"."signageos-vscode-sops" = vscode-utils.extensionFromVscodeMarketplace {
    name = "signageos-vscode-sops";
    publisher = "signageos";
    version = "0.8.0";
    sha256 = "1mjvlv3yr2ilyki5ydj8kn851rr1lmf05rm9rkv8dihhyqmdpiid";
  };

  "elagil"."pre-commit-helper" = vscode-utils.extensionFromVscodeMarketplace {
    name = "pre-commit-helper";
    publisher = "elagil";
    version = "0.4.3";
    sha256 = "1877k35biy72sh0c5f890z0mh36sr2cvd3d1mmw9mb2mdfq6xyqk";
  };
}
