# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.

{ pkgs }:

let
  vscode-utils = pkgs.vscode-utils;
in
{

  "ms-python"."python" = vscode-utils.extensionFromVscodeMarketplace {
    name = "python";
    publisher = "ms-python";
    version = "2024.0.0";
    sha256 = "0sy1z2r6b0m1lkivjyrcf41dbgj9m5zkjy6yncpji1hisjcbgq6n";
  };

  "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-pylance";
    publisher = "ms-python";
    version = "2023.12.1";
    sha256 = "03fr9zanhdsf3wirv65vb41swvdnxxaz8lviyjdbmzcw9yihf8dv";
  };

  "esbenp"."prettier-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "prettier-vscode";
    publisher = "esbenp";
    version = "10.1.0";
    sha256 = "01s0vi2h917mqfpdrhqhp2ijwkibw95yk2js0l587wvajbbry2s9";
  };

  "ms-azuretools"."vscode-docker" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-docker";
    publisher = "ms-azuretools";
    version = "1.28.0";
    sha256 = "0nmc3pdgxpmr6k2ksdczkv9bbwszncfczik0xjympqnd2k0ra9h0";
  };

  "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
    name = "gitlens";
    publisher = "eamodio";
    version = "14.7.0";
    sha256 = "07f9fryaci8lsrdahgll5yhlzf5rhscpy1zd258hi211ymvkxlmy";
  };

  "ms-vscode-remote"."remote-containers" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-containers";
    publisher = "ms-vscode-remote";
    version = "0.327.0";
    sha256 = "0asswm55bx5gpz08cgpmgfvnb0494irj0gsvzx5nwknqfzpj07lz";
  };

  "ms-vscode-remote"."remote-ssh" = vscode-utils.extensionFromVscodeMarketplace {
    name = "remote-ssh";
    publisher = "ms-vscode-remote";
    version = "0.107.1";
    sha256 = "1q9xp8id9afhjx67zc7a61zb572f296apvdz305xd5v4brqd9xrf";
  };

  "redhat"."vscode-yaml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-yaml";
    publisher = "redhat";
    version = "1.14.0";
    sha256 = "0pww9qndd2vsizsibjsvscz9fbfx8srrj67x4vhmwr581q674944";
  };

  "github"."copilot" = vscode-utils.extensionFromVscodeMarketplace {
    name = "copilot";
    publisher = "github";
    version = "1.156.0";
    sha256 = "16nzwazfbh895kmc2887b17zzbbcjyk8fhiphk5xmy1nm9qxszk0";
  };

  "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
    name = "go";
    publisher = "golang";
    version = "0.40.3";
    sha256 = "15kicpv9xpn7l3w9mbmsjdzjmavh88p3skkim0a9prg9p40bsq0m";
  };

  "gruntfuggly"."todo-tree" = vscode-utils.extensionFromVscodeMarketplace {
    name = "todo-tree";
    publisher = "gruntfuggly";
    version = "0.0.226";
    sha256 = "0yrc9qbdk7zznd823bqs1g6n2i5xrda0f9a7349kknj9wp1mqgqn";
  };

  "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-kubernetes-tools";
    publisher = "ms-kubernetes-tools";
    version = "1.3.15";
    sha256 = "1x6npc90p6b1wx5sd1hd0x0djahmffr6lw9cxh2zg10rbpq48w8i";
  };

  "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
    name = "terraform";
    publisher = "hashicorp";
    version = "2.29.3";
    sha256 = "sha256-cYYtBZaWgtT6vS6In+tbpLfp/GdyWodBXyHsxn8ZZrU=";
  };

  "ionutvmi"."path-autocomplete" = vscode-utils.extensionFromVscodeMarketplace {
    name = "path-autocomplete";
    publisher = "ionutvmi";
    version = "1.25.0";
    sha256 = "0jjqh3p456p1aafw1gl6xgxw4cqqzs3hssr74mdsmh77bjizcgcb";
  };

  "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
    name = "even-better-toml";
    publisher = "tamasfe";
    version = "0.19.2";
    sha256 = "0q9z98i446cc8bw1h1mvrddn3dnpnm2gwmzwv2s3fxdni2ggma14";
  };

  "redhat"."ansible" = vscode-utils.extensionFromVscodeMarketplace {
    name = "ansible";
    publisher = "redhat";
    version = "2.9.118";
    sha256 = "0yndj2r0w2zxc5firxgfrykkc5ajy9gsmrfmkz80kfhwk33n9y1p";
  };

  "fnando"."linter" = vscode-utils.extensionFromVscodeMarketplace {
    name = "linter";
    publisher = "fnando";
    version = "0.0.19";
    sha256 = "13bllbxd7sy4qlclh37qvvnjp1v13al11nskcf2a8pmnmj455v4g";
  };

  "catppuccin"."catppuccin-vsc" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc";
    publisher = "catppuccin";
    version = "3.11.0";
    sha256 = "12bzx1pv9pxbm08dhvl8pskpz1vg2whxmasl0qk2x54swa2rhi4d";
  };

  "catppuccin"."catppuccin-vsc-icons" = vscode-utils.extensionFromVscodeMarketplace {
    name = "catppuccin-vsc-icons";
    publisher = "catppuccin";
    version = "1.8.0";
    sha256 = "12sw9f00vnmppmvhwbamyjcap3acjs1f67mdmyv6ka52mav58z8z";
  };

  "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
    name = "nix-ide";
    publisher = "jnoortheen";
    version = "0.2.2";
    sha256 = "1264027sjh9a112si0y0p3pk3y36shj5b4qkpsj207z7lbxqq0wg";
  };

  "luisfontes19"."vscode-swissknife" = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-swissknife";
    publisher = "luisfontes19";
    version = "1.8.1";
    sha256 = "1rpk8zayzkn2kg4jjdd2fy6xl50kib71dqg73v46326cr4dwxa7c";
  };

  "elagil"."pre-commit-helper" = vscode-utils.extensionFromVscodeMarketplace {
    name = "pre-commit-helper";
    publisher = "elagil";
    version = "0.5.0";
    sha256 = "05cs1ndnha9dgv1ys23z81ajk300wpixqmks0lfmrj1zwyjg2wlj";
  };

  "shipitsmarter"."sops-edit" = vscode-utils.extensionFromVscodeMarketplace {
    name = "sops-edit";
    publisher = "shipitsmarter";
    version = "1.0.0";
    sha256 = "0b2z9khiwrpf6gxdb9y315ayqkibvgixmvx82in5rlp8pndb6sq4";
  };

  "tudoudou"."json5-for-vscode" = vscode-utils.extensionFromVscodeMarketplace {
    name = "json5-for-vscode";
    publisher = "tudoudou";
    version = "0.0.3";
    sha256 = "1d1c18mr91ll5fsp0l0aszyi7nx0ad352ssm0fm40z81m4dmzm0w";
  };
}
