---
version: "3"

tasks:
  apply-darwin:
    desc: Build and apply nix-darwin configuration
    silent: true
    requires:
      vars:
        - host
    cmds:
      - task: build-darwin
        vars:
          host: "{{ .host }}"
      - task: .prompt_to_continue
      - nix run nix-darwin -- switch --flake "{{.ROOT_DIR}}/#{{.host}}"
    preconditions:
      - sh: which nix
        msg: "nix not found"

  build-darwin:
    desc: Build nix-darwin configuration
    silent: true
    requires:
      vars:
        - host
    cmds:
      - nix run nix-darwin -- build --flake "{{.ROOT_DIR}}/#{{.host}}"
      - nvd diff /run/current-system result
    preconditions:
      - sh: which nix
        msg: "nix not found"

  deploy-nixos:
    desc: Build and deploy nixos configuration using deploy-rs
    silent: true
    summary: |
      Args:
        host: Host to build and deploy to (required)
    requires:
      vars:
        - host
    cmds:
      - nix run github:serokell/deploy-rs -- "{{.ROOT_DIR}}/#{{.host}}" --interactive --skip-checks
    preconditions:
      - sh: which nix
        msg: "nix not found"

  .prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?
