---
version: "3"

tasks:
  apply-darwin:
    desc: Build and apply nix-darwin configuration [HOST=required]
    silent: true
    preconditions:
      - which nix darwin-rebuild
    requires:
      vars:
        - HOST
    cmds:
      - task: build-darwin
        vars:
          HOST: "{{ .HOST }}"
      - task: _prompt_to_continue
      - darwin-rebuild switch --flake "{{.ROOT_DIR}}/#{{.HOST}}"

  build-darwin:
    desc: Build nix-darwin configuration [HOST=required]
    silent: true
    preconditions:
      - which nix darwin-rebuild
    requires:
      vars:
        - HOST
    cmds:
      - darwin-rebuild build --flake "{{.ROOT_DIR}}/#{{.HOST}}"
      - nvd diff /run/current-system result

  build-nixos:
    desc: Build nixos configuration [HOST=required]
    silent: true
    preconditions:
      - which nix nixos-rebuild
    requires:
      vars:
        - HOST
    vars:
      SSH_USER: bjw-s
    cmds:
      - nix-shell -p nixos-rebuild --run 'nixos-rebuild build --flake .#{{.HOST}} --fast --use-remote-sudo --build-host "{{.SSH_USER}}@{{.HOST}}.bjw-s.internal" --target-host "{{.SSH_USER}}@{{.HOST}}.bjw-s.internal"'

  apply-nixos:
    desc: Build and apply nixos configuration [HOST=required]
    silent: true
    preconditions:
      - which nix nixos-rebuild
    requires:
      vars:
        - HOST
    vars:
      SSH_USER: bjw-s
    cmds:
      - nix-shell -p nixos-rebuild --run 'nixos-rebuild switch --flake .#{{.HOST}} --fast --use-remote-sudo --build-host "{{.SSH_USER}}@{{.HOST}}.bjw-s.internal" --target-host "{{.SSH_USER}}@{{.HOST}}.bjw-s.internal"'

  _prompt_to_continue:
    internal: true
    prompt: Do you want to continue applying this configuration?
