name: Nix Lint

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
    - uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Install Nix Linting Tools
      run: nix-env -iA nixpkgs.statix

    - name: Run Statix Lint
      run: statix fix

    - name: Nix Flake Checker
      uses: DeterminateSystems/flake-checker-action@v5
